[package]

name = "msgpackio"
version = "0.0.1"
authors = []

[lib]
name="msgpackio"
path="src/lib.rs"

[[bin]]
name="dump_msgpack"
path="bin/dump_msgpack.rs"

[dependencies]
byteorder = "*"
argparse = "*"

